### ISSUE TITLE
length is undefined 

### ISSUE THREAD

**Issue by ZZcat** [jordonias/game_website#1]
![image](https://cloud.githubusercontent.com/assets/9269983/7465041/4a63c664-f28f-11e4-9cac-cb5ae49a5865.png)

**Comment by jordonias** [comment]
This is a result of no game client versions being retrieved from github. You'll need to supply a github username and password in the config. I'll have to look into why I did it this way as I am not sure.

**Comment by ZZcat** [comment]
Solved
